### ISSUE TITLE
Compare functional scores to natural mutation enrichment only in BA.1 sequences

### ISSUE THREAD

**Issue by Bernadetadad** [dms-vep/SARS-CoV-2_Omicron_BA.1_spike_DMS_mAbs#1]
@jbloom this is in relation to one reviewer's comment that they would like to see DMS functional scores compared to enrichment during natural evolution only relative to sequences from BA.1 branch. We should definitely keep the current comparison as it may be better due to just the sheer number of sequences used, but maybe we could also add those plots only for mutations in BA.1 to the same notebook.

**Comment by jbloom** [comment]
This should now be addressed in #2, which makes all the same plots etc as before but for both clades.

@Bernadetadad, if the methods previously linked to the comparison CSV with these data, you'll have to update to link the new one with extension `_csv`. Same thing for link to interactive plot.

You can see that as anticipated, the BA.1 only correlations are both worse and have many fewer mutations with enough counts.

So I think we explain to the reviewer that the power goes way down with only BA.1 included due to only ~10% as many sequences. We could potentially add this as supplementary figure, or just link to repo plot in legend of current one. 

Here are correlations for all clades (as in current draft):
<img width="1069" alt="Screen Shot 2022-12-17 at 12 59 01 PM" src="https://user-images.githubusercontent.com/1906801/208265801-996561de-0c91-460b-8d2c-636c00387e28.png">

And for BA.1 only:
<img width="994" alt="Screen Shot 2022-12-17 at 12 59 43 PM" src="https://user-images.githubusercontent.com/1906801/208265817-7fc660b2-3a49-42a7-afec-eba9b2f5dc13.png">
